apiVersion: v1
kind: ConfigMap
metadata:
  name: hoteler-web-config
data:
  backend_url: http://127.0.0.1:8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoteler-web
  labels:
    app:  hoteler-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoteler-web
  template:
    metadata:
      labels:
        app: hoteler-web
      name: hoteler-web
    spec:
      containers:
        - name: hoteler-web
          image: hoteler-web:bafc5ac
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: hoteler-web-config
                  key: backend_url
---
apiVersion: v1
kind: Service
metadata:
  name: hoteler-web
  labels:
    app:  hoteler-web
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
  selector:
    app: hoteler-web